Create CODEOWNERS
EmbarkStudios/cargo-deny-action pull request #32
Opened 2020-12-14 10:56 UTC by lpil

We are making our open source project maintainers explicit with a CODEOWNERS file. Let me know if these are not the correct maintainers for this project

### Checklist

* [ ] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [ ] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [ ] I have added a description of my changes and why I'd like them included in the section below

2020-12-14 11:16 UTC, repi commented
@Jake-Shadle should we move this to just be you that maintain it instead of me? It is really part of cargo-deny and the only thing complex in it is how to upgrade it when cargo-deny is upgraded

2020-12-14 11:20 UTC, Jake-Shadle commented
Yah that would be fine.

2020-12-14 11:25 UTC, repi requested changes

2020-12-14 11:25 UTC, repi commented on .github/CODEOWNERS
> +* @repi
```suggestion
* @JakeShadle
```

2020-12-15 11:21 UTC, lpil commented
Thanks gang

2020-12-15 11:25 UTC, repi approved these changes

2020-12-15 11:43 UTC, merged